version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ACCESS_CODE=${ACCESS_CODE}

  cloudflared-lobechat:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-lobechat
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - lobe-chat
 