version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat:latest  # ✅ correct main image
    container_name: lobe-chat
    restart: always
    depends_on:
      - postgres-db
    environment:
      # === LLM / API ===
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # You can also use OPENAI_BASE_URL or OPENROUTER_API_KEY if needed

      # === Database ===
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres-db:5432/postgres

      # === Auth / Security ===
      - ENABLE_AUTH_PROTECTION=1
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://lobe-chat.designbuildautomate.io/api/auth
      - APP_URL=https://lobe-chat.designbuildautomate.io
      - ACCESS_CODE=${ACCESS_CODE}
      - NEXT_AUTH_SSO_PROVIDERS=${NEXT_AUTH_SSO_PROVIDERS}
      - AUTH_AUTH0_ID=${AUTH_AUTH0_ID}
      - AUTH_AUTH0_SECRET=${AUTH_AUTH0_SECRET}
      - AUTH_AUTH0_ISSUER=${AUTH_AUTH0_ISSUER}

      # === Optional: R2 Storage Integration ===
      - STORAGE_TYPE=s3
      - S3_ENDPOINT=https://f3bc5d66554370eefda668ff5aa3aae2.r2.cloudflarestorage.com
      - S3_BUCKET=lobe-chat
      - S3_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - S3_REGION=auto
      - S3_PUBLIC_DOMAIN=${S3_PUBLIC_DOMAIN}

      # === Misc ===
      - KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}
      - NODE_ENV=production

    ports:
      - "3000:3000" # Optional: if you want to access it locally
    networks:
      - lobechat_net

  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: postgres-db-lobechat
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lobechat_net

  cloudflared-lobechat:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-lobechat
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - lobe-chat
    networks:
      - lobechat_net

volumes:
  postgres_data:

networks:
  lobechat_net:
    driver: bridge
